/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.pkg2.pkg1.opdr.pkg1;

import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.event.*;
import java.awt.*;

/**
 *
 * @author Gebruiker
 */
public class LoginFrame extends javax.swing.JFrame {

    Connection con;
    Statement st;
    ResultSet rs;
    static String user;
    static String pass;
    
    public LoginFrame() {
        initComponents();
        connect();
    }
    
    public void connect(){
        try{
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/DEV 2.1 Opdr 1", "postgres", "steven");
            if(con != null)
                System.out.println("Connected LoginFrame");
            st = con.createStatement();
            //String sql = "insert into servers values('', '', '')";
            //String sql = "insert into servers ('address', 'name', 'location')values('', '', '')";
            //String sql = "update servers set address='', name='', location='' where address=''";
            //String sql = "delete from servers where address=''";
            //String sql = "select user_name,password from users where user_name = ''and password = ''";
            //st.execute(sql);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void closeFrame(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOS­ING);
        Toolkit.getDefaultToolkit().getSystemEve­ntQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignupB = new javax.swing.JButton();
        LoginB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LogP = new javax.swing.JPasswordField();
        LogU = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));

        SignupB.setText("Sign Up");
        SignupB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupBActionPerformed(evt);
            }
        });

        LoginB.setText("Login");
        LoginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LogP)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(LoginB, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(SignupB, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogU))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(LogU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignupB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignupBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupBActionPerformed
        try{
            String SUuser = JOptionPane.showInputDialog(rootPane, "", "Username ?", WIDTH);
            String SUpass = JOptionPane.showInputDialog(rootPane, "", "Password ?", WIDTH);
            String SUf_name = JOptionPane.showInputDialog(rootPane, "", "First Name ?", WIDTH);
            String SUl_name = JOptionPane.showInputDialog(rootPane, "", "Last Name ?", WIDTH);
            String SUbank = JOptionPane.showInputDialog(rootPane, "", "Bank Account ?", WIDTH);
            String sql = "insert into users (user_name, first_name, last_name, iban, password) values('"+SUuser+"', '"+SUf_name+"', '"+SUl_name+"', '"+SUbank+"', '"+SUpass+"')";
            st.execute(sql);
        } catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_SignupBActionPerformed

    private void LoginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBActionPerformed
        try{
            this.pass = LogP.getText();
            this.user = LogU.getText();
            String sql = "select user_name from users where user_name = '"+user+"'";
            String sql2 = "select user_name,password from users where user_name = '"+user+"'and password = '"+pass+"'";
            rs = st.executeQuery(sql);
            
            int count = 0;
            while(rs.next()){
                count = count + 1;
            }if(count == 1){
                rs = st.executeQuery(sql2);
                int count2 = 0;
                while(rs.next()){
                    count2 = count2 + 1;
                }if(count2 == 1){
                    JOptionPane.showMessageDialog(null, "Login succes!");
                    closeFrame();
                    AccountFrame AF = new AccountFrame();
                    AF.setVisible(true);
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Password is wrong");
                }                        
            }else{
                JOptionPane.showMessageDialog(null, "Username is wrong");
            }
        } catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_LoginBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField LogP;
    private javax.swing.JTextField LogU;
    private javax.swing.JButton LoginB;
    private javax.swing.JButton SignupB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
